#!/bin/bash

#PBS -N build_cc_db
#PBS -P v45
#PBS -l storage=gdata/ik11+gdata/cj50+gdata/hh5+gdata/qv56
#PBS -l walltime=8:00:00
#PBS -l mem=48GB
#PBS -l ncpus=1
#PBS -q normalbw
#PBS -l wd
#PBS -W block=true
#PBS -j oe
#PBS -o log

# Sanity checks
if [ -z "${DB}" ]; then
  echo "Error: database to update was not provided."
  exit 1
fi

export set PYTHONNOUSERSITE=1

module purge
module use /g/data/hh5/public/modules/
module load conda/analysis3-unstable

EXPT_DIRS=()

add_dir() {
  # echo Adding $1
  EXPT_DIRS+=($1)
}

ROOT="/g/data/ik11"

WOA18="${ROOT}/observations/woa18"
add_dir $WOA18 

OUTPUTS="${ROOT}/outputs"
for d in $(find $OUTPUTS -mindepth 2 -maxdepth 2 -type d)
do
  add_dir $d 
done

JRA55="${ROOT}/inputs/JRA-55"

JRA55_do="${JRA55}/MRI-JRA55-do"
for d in ${JRA55_do}/*
do
  add_dir $d 
done

JRA55_RYF="${JRA55}/RYF/indexing"
for d in ${JRA55_RYF}/*
do
  add_dir $d 
done

GMD_PAPER="/g/data/hh5/tmp/cosima"
for d in access-om2/1deg_jra55v13_iaf_spinup1_B1 access-om2-025/025deg_jra55v13_iaf_gmredi6 access-om2-01/01deg_jra55v13_iaf
do
  d=${GMD_PAPER}/${d}
  add_dir $d 
done

CJ50="/g/data/cj50/access-om2"

CJ50_CF="${CJ50}/cf-compliant"
for d in $(find ${CJ50_CF} -mindepth 3 -maxdepth 3 -type d)
do
  add_dir $d 
done

CJ50_RAW="${CJ50}/raw-output"
for d in $(find ${CJ50_RAW} -mindepth 2 -maxdepth 2 -type d)
do
  add_dir $d 
done

cosima_cookbook-update_db -db ${DB} "${EXPT_DIRS[@]}"
