#!/bin/bash

#PBS -N build_cc_db
#PBS -P v45
#PBS -l storage=gdata/ik11+gdata/cj50+gdata/hh5+gdata/qv56
#PBS -l walltime=8:00:00
#PBS -l mem=48GB
#PBS -l ncpus=1
#PBS -q normalbw
#PBS -l wd
#PBS -W block=true
#PBS -j oe
#PBS -o log

# Sanity checks
if [ -z "${DB}" ]; then
  echo "Error: database to update was not provided."
  exit 1
fi

export set PYTHONNOUSERSITE=1

module purge
module use /g/data/hh5/public/modules/
module load conda/analysis3-unstable

cosima_cookbook-update_db -db ${DB} $(./experiment_dirs ik11 hh5 cj50)
